### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by krimo42** [Raul6469/android-gradle-action#1]
hi,
i have an issue when i try to open my project in android studio.
i have the latest version
when it try to download gradle , it display this folowing error:
Gradle sync failed: unable to find valid certification path to requested target

**Comment by Raul6469** [comment]
Hi @krimo42 👋 

It's difficult to help you with this little information...
However, it looks like this error might be an issue with your gradle file, as pointed out in [this StackOverflow answer](https://stackoverflow.com/questions/42415666/errorcause-unable-to-find-valid-certification-path-to-requested-target).

I'm closing this issue as it doesn't look like it is related to this GitHub action. Feel free to reach out if I'm wrong!
